title: Why did you go to the moon ?
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8505338078830391
  brandStrength: 0.1906999819912016
  rhythmicContrast: 0.01188473287038505
  brandColors:
    - '#D4D3D9'
    - '#3C3C3D'
    - '#DF1818'
    - '#03070B'
    - '#996753'
  lightness: 0.1741019648034126
typography_spectrum: 0.6559139
description: The importance of being ashes
navigation:
  - name: Friendshop
    id: a52d80c7-9b07-448e-9d79-54789c5b5533
    type: content
  - name: Conatus
    id: f561d1f9-438e-4c54-a3cc-33b03eba37f3
    type: content
  - name: Love&translation
    id: a0ef6cbb-ccf0-46cb-bfde-2ffae5faffca
    type: content
  - name: Freedom
    id: ec91e156-4c4f-44dc-80f3-39ff10badeab
    type: content
layout_spectrum: 0.8100358
name: Ash&trays
